repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0 # get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
